# Generated by Django 2.2.6 on 2019-11-05 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Belt_review_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='author_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
    ]
